// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(FormCosDbContext))]
    [Migration("20260209143117_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.BatteryMold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryTypeId")
                        .HasColumnType("int")
                        .HasColumnName("battery_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("BatteryTypeId");

                    b.ToTable("battery_mold");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryTypeId = 1,
                            Name = "COS-A01"
                        },
                        new
                        {
                            Id = 2,
                            BatteryTypeId = 1,
                            Name = "COS-A02"
                        },
                        new
                        {
                            Id = 3,
                            BatteryTypeId = 1,
                            Name = "COS-A03"
                        },
                        new
                        {
                            Id = 4,
                            BatteryTypeId = 2,
                            Name = "COS-B01"
                        },
                        new
                        {
                            Id = 5,
                            BatteryTypeId = 2,
                            Name = "COS-B02"
                        },
                        new
                        {
                            Id = 6,
                            BatteryTypeId = 3,
                            Name = "COS-C01"
                        },
                        new
                        {
                            Id = 7,
                            BatteryTypeId = 3,
                            Name = "COS-C02"
                        },
                        new
                        {
                            Id = 8,
                            BatteryTypeId = 3,
                            Name = "COS-C03"
                        },
                        new
                        {
                            Id = 9,
                            BatteryTypeId = 4,
                            Name = "COS-D01"
                        },
                        new
                        {
                            Id = 10,
                            BatteryTypeId = 4,
                            Name = "COS-D02"
                        },
                        new
                        {
                            Id = 11,
                            BatteryTypeId = 5,
                            Name = "COS-E01"
                        },
                        new
                        {
                            Id = 12,
                            BatteryTypeId = 5,
                            Name = "COS-E02"
                        },
                        new
                        {
                            Id = 13,
                            BatteryTypeId = 5,
                            Name = "COS-E03"
                        },
                        new
                        {
                            Id = 14,
                            BatteryTypeId = 6,
                            Name = "COS-F01"
                        },
                        new
                        {
                            Id = 15,
                            BatteryTypeId = 6,
                            Name = "COS-F02"
                        });
                });

            modelBuilder.Entity("backend.Models.BatteryStandard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryTypeId")
                        .HasColumnType("int")
                        .HasColumnName("battery_type_id");

                    b.Property<string>("ParamKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("param_key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("BatteryTypeId", "ParamKey")
                        .IsUnique();

                    b.ToTable("battery_standard");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryTypeId = 1,
                            ParamKey = "pourWait",
                            Value = "-"
                        },
                        new
                        {
                            Id = 2,
                            BatteryTypeId = 2,
                            ParamKey = "pourWait",
                            Value = "-"
                        },
                        new
                        {
                            Id = 3,
                            BatteryTypeId = 3,
                            ParamKey = "pourWait",
                            Value = "1.0 - 2.0"
                        },
                        new
                        {
                            Id = 4,
                            BatteryTypeId = 4,
                            ParamKey = "pourWait",
                            Value = "-"
                        },
                        new
                        {
                            Id = 5,
                            BatteryTypeId = 5,
                            ParamKey = "pourWait",
                            Value = "-"
                        },
                        new
                        {
                            Id = 6,
                            BatteryTypeId = 6,
                            ParamKey = "pourWait",
                            Value = "1.0 - 2.0"
                        },
                        new
                        {
                            Id = 7,
                            BatteryTypeId = 1,
                            ParamKey = "pourTime",
                            Value = ""
                        },
                        new
                        {
                            Id = 8,
                            BatteryTypeId = 2,
                            ParamKey = "pourTime",
                            Value = "2.5 - 4.0"
                        },
                        new
                        {
                            Id = 9,
                            BatteryTypeId = 3,
                            ParamKey = "pourTime",
                            Value = "1.5 - 3.0"
                        },
                        new
                        {
                            Id = 10,
                            BatteryTypeId = 4,
                            ParamKey = "pourTime",
                            Value = "3.0 - 5.0"
                        },
                        new
                        {
                            Id = 11,
                            BatteryTypeId = 5,
                            ParamKey = "pourTime",
                            Value = "3.5 - 5.5"
                        },
                        new
                        {
                            Id = 12,
                            BatteryTypeId = 6,
                            ParamKey = "pourTime",
                            Value = "1.5 - 3.0"
                        },
                        new
                        {
                            Id = 13,
                            BatteryTypeId = 1,
                            ParamKey = "dipTime2",
                            Value = ""
                        },
                        new
                        {
                            Id = 14,
                            BatteryTypeId = 2,
                            ParamKey = "dipTime2",
                            Value = "2.0 - 3.5"
                        },
                        new
                        {
                            Id = 15,
                            BatteryTypeId = 3,
                            ParamKey = "dipTime2",
                            Value = "1.0 - 2.5"
                        },
                        new
                        {
                            Id = 16,
                            BatteryTypeId = 4,
                            ParamKey = "dipTime2",
                            Value = "2.5 - 4.0"
                        },
                        new
                        {
                            Id = 17,
                            BatteryTypeId = 5,
                            ParamKey = "dipTime2",
                            Value = "3.0 - 4.5"
                        },
                        new
                        {
                            Id = 18,
                            BatteryTypeId = 6,
                            ParamKey = "dipTime2",
                            Value = "1.0 - 2.5"
                        },
                        new
                        {
                            Id = 19,
                            BatteryTypeId = 1,
                            ParamKey = "dumpTime",
                            Value = ""
                        },
                        new
                        {
                            Id = 20,
                            BatteryTypeId = 2,
                            ParamKey = "dumpTime",
                            Value = "1.5 - 3.0"
                        },
                        new
                        {
                            Id = 21,
                            BatteryTypeId = 3,
                            ParamKey = "dumpTime",
                            Value = "0.8 - 2.0"
                        },
                        new
                        {
                            Id = 22,
                            BatteryTypeId = 4,
                            ParamKey = "dumpTime",
                            Value = "2.0 - 3.5"
                        },
                        new
                        {
                            Id = 23,
                            BatteryTypeId = 5,
                            ParamKey = "dumpTime",
                            Value = "2.5 - 4.0"
                        },
                        new
                        {
                            Id = 24,
                            BatteryTypeId = 6,
                            ParamKey = "dumpTime",
                            Value = "0.8 - 2.0"
                        },
                        new
                        {
                            Id = 25,
                            BatteryTypeId = 1,
                            ParamKey = "lugDryTime",
                            Value = ""
                        },
                        new
                        {
                            Id = 26,
                            BatteryTypeId = 2,
                            ParamKey = "lugDryTime",
                            Value = "3.5 - 5.5"
                        },
                        new
                        {
                            Id = 27,
                            BatteryTypeId = 3,
                            ParamKey = "lugDryTime",
                            Value = "2.5 - 4.5"
                        },
                        new
                        {
                            Id = 28,
                            BatteryTypeId = 4,
                            ParamKey = "lugDryTime",
                            Value = "4.0 - 6.0"
                        },
                        new
                        {
                            Id = 29,
                            BatteryTypeId = 5,
                            ParamKey = "lugDryTime",
                            Value = "4.5 - 6.5"
                        },
                        new
                        {
                            Id = 30,
                            BatteryTypeId = 6,
                            ParamKey = "lugDryTime",
                            Value = "2.5 - 4.5"
                        },
                        new
                        {
                            Id = 31,
                            BatteryTypeId = 1,
                            ParamKey = "largeVibratorTime",
                            Value = ""
                        },
                        new
                        {
                            Id = 32,
                            BatteryTypeId = 2,
                            ParamKey = "largeVibratorTime",
                            Value = "1.5 - 3.5"
                        },
                        new
                        {
                            Id = 33,
                            BatteryTypeId = 3,
                            ParamKey = "largeVibratorTime",
                            Value = "0.8 - 2.5"
                        },
                        new
                        {
                            Id = 34,
                            BatteryTypeId = 4,
                            ParamKey = "largeVibratorTime",
                            Value = "2.0 - 4.0"
                        },
                        new
                        {
                            Id = 35,
                            BatteryTypeId = 5,
                            ParamKey = "largeVibratorTime",
                            Value = "2.5 - 4.5"
                        },
                        new
                        {
                            Id = 36,
                            BatteryTypeId = 6,
                            ParamKey = "largeVibratorTime",
                            Value = "0.8 - 2.5"
                        },
                        new
                        {
                            Id = 37,
                            BatteryTypeId = 1,
                            ParamKey = "smallVibratorTime",
                            Value = ""
                        },
                        new
                        {
                            Id = 38,
                            BatteryTypeId = 2,
                            ParamKey = "smallVibratorTime",
                            Value = "1.5 - 3.5"
                        },
                        new
                        {
                            Id = 39,
                            BatteryTypeId = 3,
                            ParamKey = "smallVibratorTime",
                            Value = "0.8 - 2.5"
                        },
                        new
                        {
                            Id = 40,
                            BatteryTypeId = 4,
                            ParamKey = "smallVibratorTime",
                            Value = "2.0 - 4.0"
                        },
                        new
                        {
                            Id = 41,
                            BatteryTypeId = 5,
                            ParamKey = "smallVibratorTime",
                            Value = "2.5 - 4.5"
                        },
                        new
                        {
                            Id = 42,
                            BatteryTypeId = 6,
                            ParamKey = "smallVibratorTime",
                            Value = "0.8 - 2.5"
                        },
                        new
                        {
                            Id = 43,
                            BatteryTypeId = 1,
                            ParamKey = "coolingTime",
                            Value = ""
                        },
                        new
                        {
                            Id = 44,
                            BatteryTypeId = 2,
                            ParamKey = "coolingTime",
                            Value = "25 - 35"
                        },
                        new
                        {
                            Id = 45,
                            BatteryTypeId = 3,
                            ParamKey = "coolingTime",
                            Value = "18 - 28"
                        },
                        new
                        {
                            Id = 46,
                            BatteryTypeId = 4,
                            ParamKey = "coolingTime",
                            Value = "28 - 38"
                        },
                        new
                        {
                            Id = 47,
                            BatteryTypeId = 5,
                            ParamKey = "coolingTime",
                            Value = "30 - 42"
                        },
                        new
                        {
                            Id = 48,
                            BatteryTypeId = 6,
                            ParamKey = "coolingTime",
                            Value = "18 - 28"
                        },
                        new
                        {
                            Id = 49,
                            BatteryTypeId = 1,
                            ParamKey = "leadPumpSpeed",
                            Value = ""
                        },
                        new
                        {
                            Id = 50,
                            BatteryTypeId = 2,
                            ParamKey = "leadPumpSpeed",
                            Value = "45 - 65"
                        },
                        new
                        {
                            Id = 51,
                            BatteryTypeId = 3,
                            ParamKey = "leadPumpSpeed",
                            Value = "35 - 55"
                        },
                        new
                        {
                            Id = 52,
                            BatteryTypeId = 4,
                            ParamKey = "leadPumpSpeed",
                            Value = "50 - 70"
                        },
                        new
                        {
                            Id = 53,
                            BatteryTypeId = 5,
                            ParamKey = "leadPumpSpeed",
                            Value = "55 - 75"
                        },
                        new
                        {
                            Id = 54,
                            BatteryTypeId = 6,
                            ParamKey = "leadPumpSpeed",
                            Value = "35 - 55"
                        },
                        new
                        {
                            Id = 55,
                            BatteryTypeId = 1,
                            ParamKey = "tempAirDryer",
                            Value = "300 - 400"
                        },
                        new
                        {
                            Id = 56,
                            BatteryTypeId = 2,
                            ParamKey = "tempAirDryer",
                            Value = "310 - 410"
                        },
                        new
                        {
                            Id = 57,
                            BatteryTypeId = 3,
                            ParamKey = "tempAirDryer",
                            Value = "290 - 390"
                        },
                        new
                        {
                            Id = 58,
                            BatteryTypeId = 4,
                            ParamKey = "tempAirDryer",
                            Value = "320 - 420"
                        },
                        new
                        {
                            Id = 59,
                            BatteryTypeId = 5,
                            ParamKey = "tempAirDryer",
                            Value = "330 - 430"
                        },
                        new
                        {
                            Id = 60,
                            BatteryTypeId = 6,
                            ParamKey = "tempAirDryer",
                            Value = "290 - 390"
                        },
                        new
                        {
                            Id = 61,
                            BatteryTypeId = 1,
                            ParamKey = "tempPot",
                            Value = "470 - 490"
                        },
                        new
                        {
                            Id = 62,
                            BatteryTypeId = 2,
                            ParamKey = "tempPot",
                            Value = "475 - 495"
                        },
                        new
                        {
                            Id = 63,
                            BatteryTypeId = 3,
                            ParamKey = "tempPot",
                            Value = "465 - 485"
                        },
                        new
                        {
                            Id = 64,
                            BatteryTypeId = 4,
                            ParamKey = "tempPot",
                            Value = "480 - 500"
                        },
                        new
                        {
                            Id = 65,
                            BatteryTypeId = 5,
                            ParamKey = "tempPot",
                            Value = "485 - 505"
                        },
                        new
                        {
                            Id = 66,
                            BatteryTypeId = 6,
                            ParamKey = "tempPot",
                            Value = "465 - 485"
                        },
                        new
                        {
                            Id = 67,
                            BatteryTypeId = 1,
                            ParamKey = "tempPipe",
                            Value = "410 - 430"
                        },
                        new
                        {
                            Id = 68,
                            BatteryTypeId = 2,
                            ParamKey = "tempPipe",
                            Value = "415 - 435"
                        },
                        new
                        {
                            Id = 69,
                            BatteryTypeId = 3,
                            ParamKey = "tempPipe",
                            Value = "405 - 425"
                        },
                        new
                        {
                            Id = 70,
                            BatteryTypeId = 4,
                            ParamKey = "tempPipe",
                            Value = "420 - 440"
                        },
                        new
                        {
                            Id = 71,
                            BatteryTypeId = 5,
                            ParamKey = "tempPipe",
                            Value = "425 - 445"
                        },
                        new
                        {
                            Id = 72,
                            BatteryTypeId = 6,
                            ParamKey = "tempPipe",
                            Value = "405 - 425"
                        },
                        new
                        {
                            Id = 73,
                            BatteryTypeId = 1,
                            ParamKey = "tempCrossBlock",
                            Value = "390 - 410"
                        },
                        new
                        {
                            Id = 74,
                            BatteryTypeId = 2,
                            ParamKey = "tempCrossBlock",
                            Value = "395 - 415"
                        },
                        new
                        {
                            Id = 75,
                            BatteryTypeId = 3,
                            ParamKey = "tempCrossBlock",
                            Value = "385 - 405"
                        },
                        new
                        {
                            Id = 76,
                            BatteryTypeId = 4,
                            ParamKey = "tempCrossBlock",
                            Value = "400 - 420"
                        },
                        new
                        {
                            Id = 77,
                            BatteryTypeId = 5,
                            ParamKey = "tempCrossBlock",
                            Value = "405 - 425"
                        },
                        new
                        {
                            Id = 78,
                            BatteryTypeId = 6,
                            ParamKey = "tempCrossBlock",
                            Value = "385 - 405"
                        },
                        new
                        {
                            Id = 79,
                            BatteryTypeId = 1,
                            ParamKey = "tempElbow",
                            Value = "370 - 390"
                        },
                        new
                        {
                            Id = 80,
                            BatteryTypeId = 2,
                            ParamKey = "tempElbow",
                            Value = "375 - 395"
                        },
                        new
                        {
                            Id = 81,
                            BatteryTypeId = 3,
                            ParamKey = "tempElbow",
                            Value = "365 - 385"
                        },
                        new
                        {
                            Id = 82,
                            BatteryTypeId = 4,
                            ParamKey = "tempElbow",
                            Value = "380 - 400"
                        },
                        new
                        {
                            Id = 83,
                            BatteryTypeId = 5,
                            ParamKey = "tempElbow",
                            Value = "385 - 405"
                        },
                        new
                        {
                            Id = 84,
                            BatteryTypeId = 6,
                            ParamKey = "tempElbow",
                            Value = "365 - 385"
                        },
                        new
                        {
                            Id = 85,
                            BatteryTypeId = 1,
                            ParamKey = "tempMold",
                            Value = "160 - 190"
                        },
                        new
                        {
                            Id = 86,
                            BatteryTypeId = 2,
                            ParamKey = "tempMold",
                            Value = "165 - 195"
                        },
                        new
                        {
                            Id = 87,
                            BatteryTypeId = 3,
                            ParamKey = "tempMold",
                            Value = "155 - 185"
                        },
                        new
                        {
                            Id = 88,
                            BatteryTypeId = 4,
                            ParamKey = "tempMold",
                            Value = "170 - 200"
                        },
                        new
                        {
                            Id = 89,
                            BatteryTypeId = 5,
                            ParamKey = "tempMold",
                            Value = "175 - 205"
                        },
                        new
                        {
                            Id = 90,
                            BatteryTypeId = 6,
                            ParamKey = "tempMold",
                            Value = "155 - 185"
                        },
                        new
                        {
                            Id = 91,
                            BatteryTypeId = 1,
                            ParamKey = "coolingFlowRate",
                            Value = "6 - 10"
                        },
                        new
                        {
                            Id = 92,
                            BatteryTypeId = 2,
                            ParamKey = "coolingFlowRate",
                            Value = "7 - 11"
                        },
                        new
                        {
                            Id = 93,
                            BatteryTypeId = 3,
                            ParamKey = "coolingFlowRate",
                            Value = "5 - 9"
                        },
                        new
                        {
                            Id = 94,
                            BatteryTypeId = 4,
                            ParamKey = "coolingFlowRate",
                            Value = "8 - 12"
                        },
                        new
                        {
                            Id = 95,
                            BatteryTypeId = 5,
                            ParamKey = "coolingFlowRate",
                            Value = "9 - 13"
                        },
                        new
                        {
                            Id = 96,
                            BatteryTypeId = 6,
                            ParamKey = "coolingFlowRate",
                            Value = "5 - 9"
                        });
                });

            modelBuilder.Entity("backend.Models.BatteryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("battery_type");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NS40ZL"
                        },
                        new
                        {
                            Id = 2,
                            Name = "NS60L"
                        },
                        new
                        {
                            Id = 3,
                            Name = "34B19LS"
                        },
                        new
                        {
                            Id = 4,
                            Name = "N50Z"
                        },
                        new
                        {
                            Id = 5,
                            Name = "N70Z"
                        },
                        new
                        {
                            Id = 6,
                            Name = "34B19LS OE TYT"
                        });
                });

            modelBuilder.Entity("backend.Models.CheckItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConditionalLabel")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("conditional_label");

                    b.Property<string>("FixedStandard")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fixed_standard");

                    b.Property<string>("Frequency")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("frequency");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("item_key");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("keterangan");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("label");

                    b.Property<string>("NumericStdKey")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numeric_std_key");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type");

                    b.Property<string>("VisualStandard")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("visual_standard");

                    b.HasKey("Id");

                    b.HasIndex("ItemKey")
                        .IsUnique();

                    b.ToTable("check_item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Frequency = "1 batt / shift / ganti type",
                            ItemKey = "kekuatanCastingStrap",
                            Label = "Kekuatan Casting Strap",
                            SortOrder = 1,
                            Type = "visual",
                            VisualStandard = "Ditarik tidak lepas"
                        },
                        new
                        {
                            Id = 2,
                            Frequency = "1 batt / shift / ganti type",
                            ItemKey = "meniscus",
                            Label = "Meniscus",
                            SortOrder = 2,
                            Type = "visual",
                            VisualStandard = "Positif"
                        },
                        new
                        {
                            Id = 3,
                            Frequency = "1 Batt / shift / ganti type",
                            ItemKey = "hasilCastingStrap",
                            Label = "Hasil Casting Strap",
                            SortOrder = 3,
                            Type = "visual",
                            VisualStandard = "Tidak ada flash"
                        },
                        new
                        {
                            Id = 4,
                            Frequency = "",
                            ItemKey = "levelFlux",
                            Label = "Level Flux",
                            SortOrder = 4,
                            Type = "visual",
                            VisualStandard = "Terisi Flux"
                        },
                        new
                        {
                            Id = 5,
                            ConditionalLabel = "Khusus Line 8",
                            Frequency = "2 x / Shift / ganti type",
                            ItemKey = "pourWait",
                            Label = "Pour Wait (Khusus Line 8)",
                            NumericStdKey = "pourWait",
                            SortOrder = 5,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 6,
                            Frequency = "",
                            ItemKey = "pourTime",
                            Label = "Pour Time",
                            NumericStdKey = "pourTime",
                            SortOrder = 6,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 7,
                            Frequency = "",
                            ItemKey = "dipTime2",
                            Label = "Dip Time 2",
                            NumericStdKey = "dipTime2",
                            SortOrder = 7,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 8,
                            Frequency = "",
                            ItemKey = "dumpTime",
                            Label = "Dump Time (Drain back time)",
                            NumericStdKey = "dumpTime",
                            SortOrder = 8,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 9,
                            Frequency = "2 x / Shift / ganti type",
                            ItemKey = "lugDryTime",
                            Keterangan = "untuk 34B19LS OE TYT",
                            Label = "Lug Dry Time",
                            NumericStdKey = "lugDryTime",
                            SortOrder = 9,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 10,
                            Frequency = "",
                            ItemKey = "largeVibratorTime",
                            Label = "Large Vibrator Time",
                            NumericStdKey = "largeVibratorTime",
                            SortOrder = 10,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 11,
                            Frequency = "",
                            ItemKey = "smallVibratorTime",
                            Label = "Small Vibrator Time",
                            NumericStdKey = "smallVibratorTime",
                            SortOrder = 11,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 12,
                            Frequency = "",
                            ItemKey = "coolingTime",
                            Label = "Cooling Time",
                            NumericStdKey = "coolingTime",
                            SortOrder = 12,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 13,
                            Frequency = "",
                            ItemKey = "leadPumpSpeed",
                            Label = "Lead Pump Speed",
                            NumericStdKey = "leadPumpSpeed",
                            SortOrder = 13,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 14,
                            Frequency = "1 x / shift",
                            ItemKey = "checkAlignment",
                            Label = "Check Alignment",
                            SortOrder = 14,
                            Type = "visual",
                            VisualStandard = "Bergerak"
                        },
                        new
                        {
                            Id = 15,
                            Frequency = "1 x / shift",
                            ItemKey = "checkDatumTable",
                            Keterangan = "Tidak ada ceceran pasta",
                            Label = "Check Datum Table Alignment",
                            SortOrder = 15,
                            Type = "visual",
                            VisualStandard = "Bersih"
                        },
                        new
                        {
                            Id = 16,
                            Frequency = "1 x / shift",
                            ItemKey = "cleaningNozzle",
                            Keterangan = "Spray dengan udara",
                            Label = "Cleaning of Nozzle Lug Dry",
                            SortOrder = 16,
                            Type = "visual",
                            VisualStandard = "Bersih"
                        },
                        new
                        {
                            Id = 17,
                            FixedStandard = "> 275° C",
                            Frequency = "2 x / shift",
                            ItemKey = "tempAirNozzleLugDry",
                            Keterangan = "Cek dgn Thermocouple",
                            Label = "Temp Air Nozzle Lug Dry",
                            SortOrder = 17,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 18,
                            Frequency = "2 x / shift",
                            ItemKey = "tempAirDryer",
                            Label = "Temp Air Dryer (hot air)",
                            NumericStdKey = "tempAirDryer",
                            SortOrder = 18,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 19,
                            ConditionalLabel = "Khusus Line 7",
                            FixedStandard = "> 300° C",
                            Frequency = "2 x / shift",
                            ItemKey = "blowerPipeTemp",
                            Label = "Blower Pipe Temp (Khusus Line 7)",
                            SortOrder = 19,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 20,
                            ConditionalLabel = "Khusus Line 7",
                            FixedStandard = "> 200° C",
                            Frequency = "2 x / shift",
                            ItemKey = "blowerNozzle1Temp",
                            Label = "Blower Nozzle 1 Temp (Khusus Line 7)",
                            SortOrder = 20,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 21,
                            ConditionalLabel = "Khusus Line 7",
                            FixedStandard = "> 200° C",
                            Frequency = "2 x / shift",
                            ItemKey = "blowerNozzle2Temp",
                            Label = "Blower Nozzle 2 Temp (Khusus Line 7)",
                            SortOrder = 21,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 22,
                            Frequency = "2 x / shift",
                            ItemKey = "tempPot",
                            Label = "Temperatur Pot",
                            NumericStdKey = "tempPot",
                            SortOrder = 22,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 23,
                            Frequency = "2 x / shift",
                            ItemKey = "tempPipe",
                            Label = "Temperatur Pipe",
                            NumericStdKey = "tempPipe",
                            SortOrder = 23,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 24,
                            Frequency = "2 x / shift",
                            ItemKey = "tempCrossBlock",
                            Label = "Temp. Cross Block",
                            NumericStdKey = "tempCrossBlock",
                            SortOrder = 24,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 25,
                            Frequency = "2 x / shift",
                            ItemKey = "tempElbow",
                            Label = "Temp. Elbow (Lead Lump)",
                            NumericStdKey = "tempElbow",
                            SortOrder = 25,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 26,
                            Frequency = "2 x / shift",
                            ItemKey = "tempMold",
                            Label = "Temperatur Mold",
                            NumericStdKey = "tempMold",
                            SortOrder = 26,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 27,
                            Frequency = "2 x / shift",
                            ItemKey = "coolingFlowRate",
                            Label = "Cooling Water Flow Rate",
                            NumericStdKey = "coolingFlowRate",
                            SortOrder = 27,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 28,
                            FixedStandard = "28 ± 2 °C",
                            Frequency = "2 x / shift",
                            ItemKey = "coolingWaterTemp",
                            Label = "Cooling Water Temperature",
                            SortOrder = 28,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 29,
                            Frequency = "2 x / Shift",
                            ItemKey = "sprueBrush",
                            Label = "Sprue Brush",
                            SortOrder = 29,
                            Type = "visual",
                            VisualStandard = "Berfungsi dengan baik"
                        },
                        new
                        {
                            Id = 30,
                            Frequency = "3 x / Shift",
                            ItemKey = "cleaningCavityMold",
                            Label = "Cleaning Cavity Mold COS",
                            SortOrder = 30,
                            Type = "visual",
                            VisualStandard = "Tidak tersumbat dross"
                        },
                        new
                        {
                            Id = 31,
                            Frequency = "1 batt / shift / ganti type",
                            ItemKey = "fluxTime",
                            Label = "Flux Time",
                            SortOrder = 31,
                            Type = "numeric"
                        },
                        new
                        {
                            Id = 32,
                            Frequency = "1 batt / shift / ganti type",
                            ItemKey = "overflowHydrazine",
                            Label = "Overflow Hydrazine",
                            SortOrder = 32,
                            Type = "numeric"
                        });
                });

            modelBuilder.Entity("backend.Models.CheckSubRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckItemId")
                        .HasColumnType("int")
                        .HasColumnName("check_item_id");

                    b.Property<string>("FixedStandard")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fixed_standard");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("suffix");

                    b.HasKey("Id");

                    b.HasIndex("CheckItemId");

                    b.ToTable("check_sub_row");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckItemId = 1,
                            Label = "+",
                            SortOrder = 1,
                            Suffix = "plus"
                        },
                        new
                        {
                            Id = 2,
                            CheckItemId = 1,
                            Label = "−",
                            SortOrder = 2,
                            Suffix = "minus"
                        },
                        new
                        {
                            Id = 3,
                            CheckItemId = 2,
                            Label = "+",
                            SortOrder = 1,
                            Suffix = "plus"
                        },
                        new
                        {
                            Id = 4,
                            CheckItemId = 2,
                            Label = "−",
                            SortOrder = 2,
                            Suffix = "minus"
                        },
                        new
                        {
                            Id = 5,
                            CheckItemId = 23,
                            Label = "L",
                            SortOrder = 1,
                            Suffix = "L"
                        },
                        new
                        {
                            Id = 6,
                            CheckItemId = 23,
                            Label = "R",
                            SortOrder = 2,
                            Suffix = "R"
                        },
                        new
                        {
                            Id = 7,
                            CheckItemId = 26,
                            Label = "Mold 1",
                            SortOrder = 1,
                            Suffix = "mold1"
                        },
                        new
                        {
                            Id = 8,
                            CheckItemId = 26,
                            Label = "Mold 2",
                            SortOrder = 2,
                            Suffix = "mold2"
                        },
                        new
                        {
                            Id = 9,
                            CheckItemId = 26,
                            Label = "Post 1",
                            SortOrder = 3,
                            Suffix = "post1"
                        },
                        new
                        {
                            Id = 10,
                            CheckItemId = 26,
                            Label = "Post 2",
                            SortOrder = 4,
                            Suffix = "post2"
                        },
                        new
                        {
                            Id = 11,
                            CheckItemId = 27,
                            Label = "Mold 1",
                            SortOrder = 1,
                            Suffix = "mold1"
                        },
                        new
                        {
                            Id = 12,
                            CheckItemId = 27,
                            Label = "Mold 2",
                            SortOrder = 2,
                            Suffix = "mold2"
                        },
                        new
                        {
                            Id = 13,
                            CheckItemId = 31,
                            FixedStandard = "1 - 3 detik",
                            Label = "Line 6",
                            SortOrder = 1,
                            Suffix = "line6"
                        },
                        new
                        {
                            Id = 14,
                            CheckItemId = 31,
                            FixedStandard = "0.1 - 1 detik",
                            Label = "Line 2,3,4,5,7&8",
                            SortOrder = 2,
                            Suffix = "lineOther"
                        },
                        new
                        {
                            Id = 15,
                            CheckItemId = 32,
                            FixedStandard = "10 detik",
                            Label = "Line 2",
                            SortOrder = 1,
                            Suffix = "line2"
                        },
                        new
                        {
                            Id = 16,
                            CheckItemId = 32,
                            FixedStandard = "5 detik",
                            Label = "Line 7",
                            SortOrder = 2,
                            Suffix = "line7"
                        });
                });

            modelBuilder.Entity("backend.Models.CosCheckSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CosValidationId")
                        .HasColumnType("int")
                        .HasColumnName("cos_validation_id");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("setting_key");

                    b.Property<string>("Value")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("CosValidationId", "SettingKey")
                        .IsUnique();

                    b.ToTable("cos_check_setting");
                });

            modelBuilder.Entity("backend.Models.CosProblem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("action");

                    b.Property<int>("CosValidationId")
                        .HasColumnType("int")
                        .HasColumnName("cos_validation_id");

                    b.Property<string>("Problem")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("problem");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("CosValidationId");

                    b.ToTable("cos_problem");
                });

            modelBuilder.Entity("backend.Models.CosSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CosValidationId")
                        .HasColumnType("int")
                        .HasColumnName("cos_validation_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("role");

                    b.Property<string>("SignatureData")
                        .HasColumnType("longtext")
                        .HasColumnName("signature_data");

                    b.HasKey("Id");

                    b.HasIndex("CosValidationId", "Role")
                        .IsUnique();

                    b.ToTable("cos_signature");
                });

            modelBuilder.Entity("backend.Models.CosValidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatteryType1")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("battery_type_1");

                    b.Property<string>("BatteryType2")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("battery_type_2");

                    b.Property<string>("BatteryType3")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("battery_type_3");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("KasieId")
                        .HasColumnType("int")
                        .HasColumnName("kasie_id");

                    b.Property<int?>("KasubsieId")
                        .HasColumnType("int")
                        .HasColumnName("kasubsie_id");

                    b.Property<int?>("LeaderId")
                        .HasColumnType("int")
                        .HasColumnName("leader_id");

                    b.Property<int>("Line")
                        .HasColumnType("int")
                        .HasColumnName("line");

                    b.Property<string>("Mold1")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mold_1");

                    b.Property<string>("Mold2")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mold_2");

                    b.Property<string>("Mold3")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mold_3");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int")
                        .HasColumnName("operator_id");

                    b.Property<int>("Shift")
                        .HasColumnType("int")
                        .HasColumnName("shift");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tanggal");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KasieId");

                    b.HasIndex("KasubsieId");

                    b.HasIndex("LeaderId");

                    b.HasIndex("OperatorId");

                    b.ToTable("cos_validation");
                });

            modelBuilder.Entity("backend.Models.Kasie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("kasie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kurniawan Adi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sutrisno Hadi"
                        });
                });

            modelBuilder.Entity("backend.Models.Kasubsie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KasieId")
                        .HasColumnType("int")
                        .HasColumnName("kasie_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("KasieId");

                    b.ToTable("kasubsie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KasieId = 1,
                            Name = "Joko Prasetyo"
                        },
                        new
                        {
                            Id = 2,
                            KasieId = 1,
                            Name = "Mulyono Slamet"
                        },
                        new
                        {
                            Id = 3,
                            KasieId = 2,
                            Name = "Teguh Wibowo"
                        });
                });

            modelBuilder.Entity("backend.Models.Leader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KasubsieId")
                        .HasColumnType("int")
                        .HasColumnName("kasubsie_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("KasubsieId");

                    b.ToTable("leader");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KasubsieId = 1,
                            Name = "Hendra Wijaya"
                        },
                        new
                        {
                            Id = 2,
                            KasubsieId = 1,
                            Name = "Irfan Hakim"
                        },
                        new
                        {
                            Id = 3,
                            KasubsieId = 2,
                            Name = "Fajar Nugroho"
                        },
                        new
                        {
                            Id = 4,
                            KasubsieId = 3,
                            Name = "Dedi Kurniawan"
                        });
                });

            modelBuilder.Entity("backend.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LeaderId")
                        .HasColumnType("int")
                        .HasColumnName("leader_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.ToTable("operator");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeaderId = 1,
                            Name = "Ahmad Rizky"
                        },
                        new
                        {
                            Id = 2,
                            LeaderId = 1,
                            Name = "Budi Santoso"
                        },
                        new
                        {
                            Id = 3,
                            LeaderId = 2,
                            Name = "Cahya Dewi"
                        },
                        new
                        {
                            Id = 4,
                            LeaderId = 2,
                            Name = "Dian Permata"
                        },
                        new
                        {
                            Id = 5,
                            LeaderId = 3,
                            Name = "Eko Prasetyo"
                        },
                        new
                        {
                            Id = 6,
                            LeaderId = 3,
                            Name = "Faisal Rahman"
                        },
                        new
                        {
                            Id = 7,
                            LeaderId = 4,
                            Name = "Gunawan Putra"
                        },
                        new
                        {
                            Id = 8,
                            LeaderId = 4,
                            Name = "Haris Munandar"
                        });
                });

            modelBuilder.Entity("backend.Models.BatteryMold", b =>
                {
                    b.HasOne("backend.Models.BatteryType", "BatteryType")
                        .WithMany("Molds")
                        .HasForeignKey("BatteryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatteryType");
                });

            modelBuilder.Entity("backend.Models.BatteryStandard", b =>
                {
                    b.HasOne("backend.Models.BatteryType", "BatteryType")
                        .WithMany("Standards")
                        .HasForeignKey("BatteryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatteryType");
                });

            modelBuilder.Entity("backend.Models.CheckSubRow", b =>
                {
                    b.HasOne("backend.Models.CheckItem", "CheckItem")
                        .WithMany("SubRows")
                        .HasForeignKey("CheckItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckItem");
                });

            modelBuilder.Entity("backend.Models.CosCheckSetting", b =>
                {
                    b.HasOne("backend.Models.CosValidation", "CosValidation")
                        .WithMany("CheckSettings")
                        .HasForeignKey("CosValidationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CosValidation");
                });

            modelBuilder.Entity("backend.Models.CosProblem", b =>
                {
                    b.HasOne("backend.Models.CosValidation", "CosValidation")
                        .WithMany("Problems")
                        .HasForeignKey("CosValidationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CosValidation");
                });

            modelBuilder.Entity("backend.Models.CosSignature", b =>
                {
                    b.HasOne("backend.Models.CosValidation", "CosValidation")
                        .WithMany("Signatures")
                        .HasForeignKey("CosValidationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CosValidation");
                });

            modelBuilder.Entity("backend.Models.CosValidation", b =>
                {
                    b.HasOne("backend.Models.Kasie", "Kasie")
                        .WithMany()
                        .HasForeignKey("KasieId");

                    b.HasOne("backend.Models.Kasubsie", "Kasubsie")
                        .WithMany()
                        .HasForeignKey("KasubsieId");

                    b.HasOne("backend.Models.Leader", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId");

                    b.HasOne("backend.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kasie");

                    b.Navigation("Kasubsie");

                    b.Navigation("Leader");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("backend.Models.Kasubsie", b =>
                {
                    b.HasOne("backend.Models.Kasie", "Kasie")
                        .WithMany("Kasubsies")
                        .HasForeignKey("KasieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kasie");
                });

            modelBuilder.Entity("backend.Models.Leader", b =>
                {
                    b.HasOne("backend.Models.Kasubsie", "Kasubsie")
                        .WithMany("Leaders")
                        .HasForeignKey("KasubsieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kasubsie");
                });

            modelBuilder.Entity("backend.Models.Operator", b =>
                {
                    b.HasOne("backend.Models.Leader", "Leader")
                        .WithMany("Operators")
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("backend.Models.BatteryType", b =>
                {
                    b.Navigation("Molds");

                    b.Navigation("Standards");
                });

            modelBuilder.Entity("backend.Models.CheckItem", b =>
                {
                    b.Navigation("SubRows");
                });

            modelBuilder.Entity("backend.Models.CosValidation", b =>
                {
                    b.Navigation("CheckSettings");

                    b.Navigation("Problems");

                    b.Navigation("Signatures");
                });

            modelBuilder.Entity("backend.Models.Kasie", b =>
                {
                    b.Navigation("Kasubsies");
                });

            modelBuilder.Entity("backend.Models.Kasubsie", b =>
                {
                    b.Navigation("Leaders");
                });

            modelBuilder.Entity("backend.Models.Leader", b =>
                {
                    b.Navigation("Operators");
                });
#pragma warning restore 612, 618
        }
    }
}
